[workspace]
resolver = "2"

members = [
  "clientie",
  "registrie",
  "schemou",

  # Internals
  "xtasks"
]

[profile.release.package.clientie]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
