[package]
name = "schemou"
version = "0.0.1-pr"
edition = "2021"

[dependencies]
sirius = { git = "https://github.com/thatmagicalcat/sirius", rev = "fbb60cafa3dc2e47a12f40c5108f00756b286943" }
axum = { version = "0.8", optional = true }

[features]
axum = ["dep:axum"]
