name: Rust

on:
  pull_request:
    branches: [ "main" ]

env:
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check and Lint
      run: cargo clippy --verbose
    - name: Build and Test
      run: cargo test --verbose
